-- Create Bonus Employees Table
create table if not exists bonus_employees (
  id bigint generated by default as identity primary key,
  username text unique not null,
  full_name text not null,
  password text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Bonuses Table
create table if not exists bonuses (
  id bigint generated by default as identity primary key,
  employee_id bigint references bonus_employees(id) on delete cascade,
  sale_date date not null default current_date,
  amount numeric not null default 0,
  invoice_url text, -- Supabase Storage URL
  status text not null default 'pending' check (status in ('pending', 'approved', 'paid')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Optional but recommended)
-- alter table bonus_employees enable row level security;
-- alter table bonuses enable row level security;

-- Instructions for Supabase Storage:
-- 1. Create a bucket named "bonus-invoices"
-- 2. Set the bucket to "Public" or set appropriate RLS policies for public access.
