-- Drop existing tables to ensure a clean slate
drop table if exists influencers cascade;
drop table if exists campaigns cascade;
drop table if exists coupons cascade;
drop table if exists events cascade;
drop table if exists banners cascade;
drop table if exists banner_schedule cascade;
drop table if exists meetings cascade;
drop table if exists projects cascade;
drop table if exists marketing_tasks cascade;
drop table if exists system_logs cascade;

-- Create Influencers Table
create table influencers (
  id bigint generated by default as identity primary key,
  name text not null,
  coupon text,
  channels text,
  products text,
  base_salary numeric default 0,
  bonus_percent numeric default 0,
  sales numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Campaigns Table
create table campaigns (
  id bigint generated by default as identity primary key,
  link text,
  source text,
  type text,
  content text,
  start_date text,
  clicks numeric default 0,
  sales numeric default 0,
  budget numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Coupons Table
create table coupons (
  id bigint generated by default as identity primary key,
  code text not null,
  channel text,
  start_date text,
  end_date text,
  days numeric default 0,
-- Drop existing tables to ensure a clean slate
drop table if exists influencers cascade;
drop table if exists campaigns cascade;
drop table if exists coupons cascade;
drop table if exists events cascade;
drop table if exists banners cascade;
drop table if exists banner_schedule cascade;
drop table if exists meetings cascade;
drop table if exists projects cascade;
drop table if exists marketing_tasks cascade;
drop table if exists system_logs cascade;

-- Create Influencers Table
create table influencers (
  id bigint generated by default as identity primary key,
  name text not null,
  coupon text,
  channels text,
  products text,
  base_salary numeric default 0,
  bonus_percent numeric default 0,
  sales numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Campaigns Table
create table campaigns (
  id bigint generated by default as identity primary key,
  link text,
  source text,
  type text,
  content text,
  start_date text,
  clicks numeric default 0,
  sales numeric default 0,
  budget numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Coupons Table
create table coupons (
  id bigint generated by default as identity primary key,
  code text not null,
  channel text,
  start_date text,
  end_date text,
  days numeric default 0,
  views numeric default 0,
  sales numeric default 0,
  active text default 'פעיל',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Events Table
create table events (
  id bigint generated by default as identity primary key,
  date timestamp with time zone not null,
  influencer_id bigint,
  channel text,
  products text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Banners Table
create table banners (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date text,
  end_date text,
  status text,
  budget numeric default 0,
  clicks numeric default 0,
  views numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Banner Schedule Table (for BannersPage)
create table banner_schedule (
  id bigint generated by default as identity primary key,
  month text not null,
  banner1 text,
  banner2 text,
  banner3 text,
  replacement_date text,
  request_date text,
  performed_by text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Meetings Table
create table meetings (
  id bigint generated by default as identity primary key,
  title text not null,
  date text,
  time text,
  participants text,
  location text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Projects Table
create table projects (
  id bigint generated by default as identity primary key,
  name text not null,
  status text,
  urgency text, -- New column
  progress numeric default 0,
  due_date text,
  team text,
  notes text, -- New column
  budget numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Marketing Tasks Table
create table marketing_tasks (
  id bigint generated by default as identity primary key,
  task_name text not null,
  execution_date text,
  status text,
  urgency text,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- Create System Logs Table
create table system_logs (
  id bigint generated by default as identity primary key,
  event_type text not null,
  event_date text not null,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Shifts Table
create table shifts (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  is_vacation boolean default false,
  category text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Store Reviews Table
create table store_reviews (
  id bigint generated by default as identity primary key,
  review_date date not null,
  
  -- Cleanliness & Order
  cleanliness_score numeric,
  warehouse_organization_score numeric,
  shelf_arrangement_score numeric,
  floor_cleanliness_score numeric,
  stock_in_display_score numeric,
  drawer_order_score numeric,
  
  -- Money
  cash_register_score numeric,
  
  -- Communication & Response
  employee_appearance_score numeric,
  opening_on_time_score numeric,
  whatsapp_response_score numeric,
  phone_response_score numeric,
  story_photo_score numeric,
  music_score numeric,
  
  -- Metadata
  morning_employee text,
  evening_employee text,
  total_score numeric,
  notes text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- Create Warehouse Shipments Table
create table warehouse_shipments (
  id bigint generated by default as identity primary key,
  shipment_number text not null,
  entered_at timestamp with time zone default timezone('utc', now()) not null
);
